"""Identifier generation and validation.

Three families of identifier exist in the platform, with deliberately different
properties:

``trace_id`` / ``span_id``
    W3C Trace Context identifiers: 16 and 8 random bytes, rendered lowercase
    hex. They are generated by the *client*, must be treated as untrusted, and
    are validated on ingestion. The all-zero value is invalid per the spec.

``resource ids`` (``prj_``, ``key_``, ``org_`` ...)
    Server-generated, prefixed, sortable identifiers. The prefix makes logs and
    error messages self-describing and makes it impossible to pass a project id
    where an API key id is expected. The body is a 128-bit random value encoded
    with Crockford base32 (no ambiguous characters), preceded by a millisecond
    timestamp so identifiers sort chronologically in an index.

``version ids``
    Derived from the content hash -- see :mod:`aiobs_schemas.canonical`. They
    are not random at all: the same content always yields the same identifier,
    which is what makes prompt/model/dataset versions reproducible.
"""

from __future__ import annotations

import re
import secrets
import time
from typing import Final

__all__ = [
    "INVALID_SPAN_ID",
    "INVALID_TRACE_ID",
    "IdPrefix",
    "generate_id",
    "generate_span_id",
    "generate_trace_id",
    "is_valid_span_id",
    "is_valid_trace_id",
    "normalize_span_id",
    "normalize_trace_id",
    "parse_id",
    "version_id",
]

INVALID_TRACE_ID: Final = "0" * 32
INVALID_SPAN_ID: Final = "0" * 16

_TRACE_ID_RE: Final = re.compile(r"^[0-9a-f]{32}$")
_SPAN_ID_RE: Final = re.compile(r"^[0-9a-f]{16}$")

# Crockford base32: excludes I, L, O and U to avoid transcription errors.
_ALPHABET: Final = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
_ID_BODY_RE: Final = re.compile(r"^[0-9A-HJKMNP-TV-Z]{26}$")


class IdPrefix:
    """Registry of resource identifier prefixes.

    Prefixes are three to four characters so that identifiers stay readable in
    URLs and log lines while remaining unambiguous.
    """

    ORGANIZATION: Final = "org"
    USER: Final = "usr"
    MEMBERSHIP: Final = "mbr"
    PROJECT: Final = "prj"
    ENVIRONMENT: Final = "env"
    API_KEY: Final = "key"
    SERVICE_ACCOUNT: Final = "svc"
    PROMPT: Final = "pmt"
    PROMPT_VERSION: Final = "pmv"
    MODEL: Final = "mdl"
    MODEL_VERSION: Final = "mdv"
    DATASET: Final = "dst"
    DATASET_VERSION: Final = "dsv"
    EXPERIMENT: Final = "exp"
    EXPERIMENT_RUN: Final = "exr"
    PRICE_BOOK: Final = "pbk"
    PRICE_ENTRY: Final = "pbe"
    RETENTION_POLICY: Final = "ret"
    AUDIT_EVENT: Final = "aud"
    EXPORT: Final = "exl"
    SAVED_VIEW: Final = "svw"
    INGEST_BATCH: Final = "bat"
    OBJECT: Final = "obj"
    SESSION: Final = "ses"

    ALL: Final[frozenset[str]] = frozenset(
        {
            "org",
            "usr",
            "mbr",
            "prj",
            "env",
            "key",
            "svc",
            "pmt",
            "pmv",
            "mdl",
            "mdv",
            "dst",
            "dsv",
            "exp",
            "exr",
            "pbk",
            "pbe",
            "ret",
            "aud",
            "exl",
            "svw",
            "bat",
            "obj",
            "ses",
        }
    )


def _encode_base32(value: int, length: int) -> str:
    chars: list[str] = []
    for _ in range(length):
        chars.append(_ALPHABET[value & 0x1F])
        value >>= 5
    return "".join(reversed(chars))


def generate_id(prefix: str, *, now_ms: int | None = None) -> str:
    """Return a new prefixed, time-sortable resource identifier.

    The layout is ``<prefix>_<10 chars of ms timestamp><16 chars of randomness>``
    which is a ULID in Crockford base32 with a human-readable prefix. Sorting
    the string sorts by creation time, which keeps B-tree index inserts
    append-mostly instead of scattering them across the keyspace the way a
    random UUIDv4 primary key does.
    """
    if prefix not in IdPrefix.ALL:
        raise ValueError(f"unknown identifier prefix {prefix!r}")
    timestamp = int(time.time() * 1000) if now_ms is None else now_ms
    if not 0 <= timestamp < (1 << 48):
        raise ValueError(f"timestamp {timestamp} out of range for a 48-bit ULID")
    randomness = secrets.randbits(80)
    return f"{prefix}_{_encode_base32(timestamp, 10)}{_encode_base32(randomness, 16)}"


def parse_id(value: str) -> tuple[str, str]:
    """Split a resource identifier into ``(prefix, body)`` and validate both.

    Raises :class:`ValueError` on anything malformed. Callers use this to reject
    identifiers of the wrong type *before* a database round-trip, which turns a
    whole class of authorisation-confusion bugs into 400 responses.
    """
    prefix, separator, body = value.partition("_")
    if not separator:
        raise ValueError(f"identifier {value!r} is missing its type prefix")
    if prefix not in IdPrefix.ALL:
        raise ValueError(f"unknown identifier prefix {prefix!r}")
    if not _ID_BODY_RE.match(body):
        raise ValueError(f"identifier body {body!r} is not 26 Crockford base32 characters")
    return prefix, body


def generate_trace_id() -> str:
    """Return a random, valid W3C trace id as 32 lowercase hex characters."""
    while True:
        value = secrets.token_hex(16)
        if value != INVALID_TRACE_ID:
            return value


def generate_span_id() -> str:
    """Return a random, valid W3C span id as 16 lowercase hex characters."""
    while True:
        value = secrets.token_hex(8)
        if value != INVALID_SPAN_ID:
            return value


def is_valid_trace_id(value: str | None) -> bool:
    """Whether ``value`` is a well-formed, non-zero W3C trace id."""
    return bool(value) and bool(_TRACE_ID_RE.match(value or "")) and value != INVALID_TRACE_ID


def is_valid_span_id(value: str | None) -> bool:
    """Whether ``value`` is a well-formed, non-zero W3C span id."""
    return bool(value) and bool(_SPAN_ID_RE.match(value or "")) and value != INVALID_SPAN_ID


def normalize_trace_id(value: str | bytes) -> str:
    """Coerce a trace id from hex text or raw bytes into canonical hex form.

    OTLP/protobuf carries ids as raw bytes while OTLP/JSON carries them as hex,
    and some producers emit uppercase. Ingestion normalises once, here, so that
    every downstream comparison is a plain string equality check.
    """
    text = value.hex() if isinstance(value, (bytes, bytearray)) else str(value).strip().lower()
    if not is_valid_trace_id(text):
        raise ValueError(f"invalid trace id {value!r}")
    return text


def normalize_span_id(value: str | bytes) -> str:
    """Coerce a span id from hex text or raw bytes into canonical hex form."""
    text = value.hex() if isinstance(value, (bytes, bytearray)) else str(value).strip().lower()
    if not is_valid_span_id(text):
        raise ValueError(f"invalid span id {value!r}")
    return text


def version_id(prefix: str, content_hash_value: str) -> str:
    """Derive a deterministic version identifier from a content hash.

    Unlike :func:`generate_id` this is a pure function: publishing identical
    content twice yields the same identifier, so a re-published prompt collapses
    onto the existing version instead of forking history.
    """
    if prefix not in IdPrefix.ALL:
        raise ValueError(f"unknown identifier prefix {prefix!r}")
    algorithm, separator, digest = content_hash_value.partition(":")
    if not separator or algorithm != "sha256" or len(digest) != 64:
        raise ValueError(
            f"expected a 'sha256:' prefixed 64-character hash, got {content_hash_value!r}"
        )
    # 26 base32 characters carry 130 bits; take the leading 128 bits of the digest.
    return f"{prefix}_{_encode_base32(int(digest[:32], 16), 26)}"
