"""initial schema

Revision ID: da26712ea820
Revises: 
Created: 2026-08-01 08:38:51.710161+00:00

Rollback notes
--------------
Describe here what `downgrade()` cannot restore. A migration that drops a
column is not reversible: the downgrade recreates the column but the data is
gone. Say so explicitly -- an operator reading this at 3am needs to know
whether a rollback is safe or whether a restore is required.
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import postgresql
import sqlalchemy as sa

revision: str = 'da26712ea820'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_dead_letters',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('consumer_group', sa.String(length=128), nullable=False),
    sa.Column('original_offset', sa.BigInteger(), nullable=False),
    sa.Column('partition_key', sa.String(length=256), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('headers', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=128), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('first_failed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dead_lettered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('replayed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bus_dead_letters'))
    )
    with op.batch_alter_table('bus_dead_letters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bus_dead_letters_dead_lettered_at'), ['dead_lettered_at'], unique=False)
        batch_op.create_index('ix_bus_dead_letters_pending', ['topic', 'replayed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_bus_dead_letters_topic'), ['topic'], unique=False)

    op.create_table('bus_messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('partition', sa.Integer(), nullable=False),
    sa.Column('partition_key', sa.String(length=256), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('headers', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bus_messages'))
    )
    with op.batch_alter_table('bus_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bus_messages_topic'), ['topic'], unique=False)
        batch_op.create_index('ix_bus_messages_topic_partition_id', ['topic', 'partition', 'id'], unique=False)

    op.create_table('bus_offsets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('consumer_group', sa.String(length=128), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('partition', sa.Integer(), nullable=False),
    sa.Column('committed_offset', sa.BigInteger(), nullable=False),
    sa.Column('lease_owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bus_offsets')),
    sa.UniqueConstraint('consumer_group', 'topic', 'partition', name='one_offset_per_group_partition')
    )
    op.create_table('organizations',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_spans_per_day', sa.Integer(), nullable=False),
    sa.Column('max_projects', sa.Integer(), nullable=False),
    sa.Column('max_storage_bytes', sa.BigInteger(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(slug) >= 2', name=op.f('ck_organizations_slug_min_length')),
    sa.CheckConstraint('max_spans_per_day > 0', name=op.f('ck_organizations_positive_span_quota')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('outbox_messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=False),
    sa.Column('partition_key', sa.String(length=256), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('headers', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_messages'))
    )
    with op.batch_alter_table('outbox_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_outbox_unpublished', ['published_at', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('oidc_subject', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_epoch', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_oidc_subject'), ['oidc_subject'], unique=False)
        batch_op.create_index('ix_users_oidc_subject_unique', ['oidc_subject'], unique=True)

    op.create_table('audit_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.String(length=40), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_label', sa.String(length=320), nullable=True),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.CheckConstraint("outcome IN ('success','denied','error')", name=op.f('ck_audit_events_known_outcome')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index('ix_audit_events_org_action_occurred', ['organization_id', 'action', 'occurred_at'], unique=False)
        batch_op.create_index('ix_audit_events_org_occurred', ['organization_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_id'), ['resource_id'], unique=False)

    op.create_table('export_jobs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('requested_by', sa.String(length=40), nullable=False),
    sa.Column('resource', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('query', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('redacted', sa.Boolean(), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.CheckConstraint("format IN ('jsonl','csv','json')", name=op.f('ck_export_jobs_known_export_format')),
    sa.CheckConstraint("status IN ('queued','running','completed','failed','expired')", name=op.f('ck_export_jobs_known_export_status')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_export_jobs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_jobs'))
    )
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_export_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_export_jobs_org_status', ['organization_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_export_jobs_requested_by'), ['requested_by'], unique=False)

    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('endpoint', sa.String(length=256), nullable=False),
    sa.Column('request_fingerprint', sa.String(length=80), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.CheckConstraint("state IN ('in_progress','completed','failed')", name=op.f('ck_idempotency_records_known_idem_state')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_idempotency_records_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('organization_id', 'endpoint', 'idempotency_key', name='unique_idempotency_key')
    )
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_records_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_idempotency_records_organization_id'), ['organization_id'], unique=False)

    op.create_table('ingest_batches',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('environment_id', sa.String(length=40), nullable=False),
    sa.Column('api_key_id', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('span_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('payload_bytes', sa.BigInteger(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('sdk_name', sa.String(length=128), nullable=True),
    sa.Column('sdk_version', sa.String(length=64), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ingest_batches_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingest_batches'))
    )
    with op.batch_alter_table('ingest_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_batches_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index('ix_ingest_batches_org_received', ['organization_id', 'received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_batches_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_batches_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_batches_received_at'), ['received_at'], unique=False)

    op.create_table('memberships',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('user_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('project_scope', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('invited_by', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('owner','administrator','developer','analyst','viewer')", name=op.f('ck_memberships_known_role')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memberships_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_memberships_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memberships')),
    sa.UniqueConstraint('organization_id', 'user_id', name='one_membership_per_user_per_org')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('model_definitions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_identifier', sa.String(length=256), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=True),
    sa.Column('endpoint_kind', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('provider_metadata', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_model_definitions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_definitions')),
    sa.UniqueConstraint('organization_id', 'provider', 'model_identifier', name='unique_model_per_org')
    )
    with op.batch_alter_table('model_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_definitions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_definitions_project_id'), ['project_id'], unique=False)

    op.create_table('price_books',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=512), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_by', sa.String(length=40), nullable=True),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(currency) = 3', name=op.f('ck_price_books_currency_is_iso4217')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_price_books_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_books')),
    sa.UniqueConstraint('organization_id', 'version', name='unique_price_book_version')
    )
    with op.batch_alter_table('price_books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_books_organization_id'), ['organization_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('default_sampling_rate', sa.Float(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('default_sampling_rate >= 0 AND default_sampling_rate <= 1', name=op.f('ck_projects_sampling_rate_range')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_projects_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('organization_id', 'slug', name='unique_project_slug_per_org')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_organization_id'), ['organization_id'], unique=False)

    op.create_table('service_accounts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('secret_hash', sa.Text(), nullable=False),
    sa.Column('project_scope', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("role IN ('owner','administrator','developer','analyst','viewer')", name=op.f('ck_service_accounts_known_service_account_role')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_service_accounts_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_accounts')),
    sa.UniqueConstraint('organization_id', 'name', name='unique_service_account_name_per_org')
    )
    with op.batch_alter_table('service_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_accounts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_accounts_prefix'), ['prefix'], unique=True)

    op.create_table('stored_objects',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=80), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=True),
    sa.Column('owner_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_stored_objects_non_negative_size')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_stored_objects_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stored_objects')),
    sa.UniqueConstraint('object_key', name=op.f('uq_stored_objects_object_key'))
    )
    with op.batch_alter_table('stored_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stored_objects_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_objects_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index('ix_stored_objects_expiry_sweep', ['expires_at', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_objects_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_objects_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_objects_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_objects_project_id'), ['project_id'], unique=False)

    op.create_table('datasets',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('license', sa.String(length=256), nullable=True),
    sa.Column('contains_sensitive_data', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_datasets_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_datasets_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_datasets')),
    sa.UniqueConstraint('project_id', 'name', name='unique_dataset_name_per_project')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_datasets_project_id'), ['project_id'], unique=False)

    op.create_table('environments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_production', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_environments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_environments_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments')),
    sa.UniqueConstraint('project_id', 'name', name='unique_environment_name_per_project')
    )
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_environments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_environments_project_id'), ['project_id'], unique=False)

    op.create_table('experiments',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_experiments_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_experiments_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments')),
    sa.UniqueConstraint('project_id', 'name', name='unique_experiment_name_per_project')
    )
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiments_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiments_project_id'), ['project_id'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('model_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('config_hash', sa.String(length=80), nullable=False),
    sa.Column('deployment_name', sa.String(length=256), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('api_version', sa.String(length=64), nullable=True),
    sa.Column('adapter_version', sa.String(length=64), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('stop_sequences', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('tool_config', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('response_format', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('safety_settings', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('retry_policy', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('timeout_policy', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('provider_extras', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('system_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('release_stage', sa.String(length=16), nullable=False),
    sa.Column('parent_version_id', sa.String(length=40), nullable=True),
    sa.Column('author_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.CheckConstraint("release_stage IN ('draft','published','deprecated','archived')", name=op.f('ck_model_versions_known_model_release_stage')),
    sa.CheckConstraint('temperature IS NULL OR (temperature >= 0 AND temperature <= 2)', name=op.f('ck_model_versions_temperature_range')),
    sa.CheckConstraint('top_p IS NULL OR (top_p >= 0 AND top_p <= 1)', name=op.f('ck_model_versions_top_p_range')),
    sa.ForeignKeyConstraint(['model_id'], ['model_definitions.id'], name=op.f('fk_model_versions_model_id_model_definitions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_model_versions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_versions')),
    sa.UniqueConstraint('model_id', 'config_hash', name='unique_model_config_hash'),
    sa.UniqueConstraint('model_id', 'version_number', name='unique_model_version_number')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_config_hash'), ['config_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_model_id'), ['model_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_project_id'), ['project_id'], unique=False)

    op.create_table('price_entries',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('price_book_id', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model_identifier', sa.String(length=256), nullable=False),
    sa.Column('usage_category', sa.String(length=64), nullable=False),
    sa.Column('unit_quantity', sa.BigInteger(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=38, scale=18).with_variant(sa.String(64), 'sqlite'), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tier_min_units', sa.BigInteger(), nullable=False),
    sa.Column('tier_max_units', sa.BigInteger(), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=38, scale=18).with_variant(sa.String(64), 'sqlite'), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name=op.f('ck_price_entries_validity_window_ordering')),
    sa.CheckConstraint('length(currency) = 3', name=op.f('ck_price_entries_entry_currency_is_iso4217')),
    sa.CheckConstraint('tier_max_units IS NULL OR tier_max_units > tier_min_units', name=op.f('ck_price_entries_tier_ordering')),
    sa.CheckConstraint('tier_min_units >= 0', name=op.f('ck_price_entries_non_negative_tier_min')),
    sa.CheckConstraint('unit_quantity > 0', name=op.f('ck_price_entries_positive_unit_quantity')),
    sa.ForeignKeyConstraint(['price_book_id'], ['price_books.id'], name=op.f('fk_price_entries_price_book_id_price_books'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_entries'))
    )
    with op.batch_alter_table('price_entries', schema=None) as batch_op:
        batch_op.create_index('ix_price_entries_book_model', ['price_book_id', 'provider', 'model_identifier'], unique=False)
        batch_op.create_index('ix_price_entries_lookup', ['provider', 'model_identifier', 'usage_category', 'effective_from'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_entries_price_book_id'), ['price_book_id'], unique=False)

    op.create_table('prompts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_prompts_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_prompts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompts')),
    sa.UniqueConstraint('project_id', 'name', name='unique_prompt_name_per_project')
    )
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompts_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompts_project_id'), ['project_id'], unique=False)

    op.create_table('retention_policies',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('environment_id', sa.String(length=40), nullable=True),
    sa.Column('raw_span_days', sa.Integer(), nullable=False),
    sa.Column('aggregate_days', sa.Integer(), nullable=False),
    sa.Column('payload_days', sa.Integer(), nullable=False),
    sa.Column('purge_on_expiry', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=40), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('payload_days <= raw_span_days', name=op.f('ck_retention_policies_payload_within_span_retention')),
    sa.CheckConstraint('payload_days >= 1', name=op.f('ck_retention_policies_positive_payload_days')),
    sa.CheckConstraint('raw_span_days <= aggregate_days', name=op.f('ck_retention_policies_spans_within_aggregate_retention')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_retention_policies_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_retention_policies_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_retention_policies')),
    sa.UniqueConstraint('project_id', 'environment_id', name='one_policy_per_scope')
    )
    with op.batch_alter_table('retention_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_retention_policies_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retention_policies_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_retention_policies_project_id'), ['project_id'], unique=False)

    op.create_table('saved_views',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('query', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_saved_views_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_saved_views_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_views')),
    sa.UniqueConstraint('project_id', 'created_by', 'name', name='unique_view_name_per_owner')
    )
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_views_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_views_project_id'), ['project_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('environment_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('prefix', sa.String(length=32), nullable=False),
    sa.Column('secret_hash', sa.Text(), nullable=False),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=40), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.String(length=40), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('revoked_at IS NULL OR revoked_at >= created_at', name=op.f('ck_api_keys_revoked_after_created')),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_api_keys_environment_id_environments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_api_keys_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_api_keys_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys'))
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_environment_id'), ['environment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=True)
        batch_op.create_index('ix_api_keys_project_active', ['project_id', 'revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_project_id'), ['project_id'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('dataset_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('dataset_hash', sa.String(length=80), nullable=False),
    sa.Column('record_schema', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('total_bytes', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=512), nullable=True),
    sa.Column('splits', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('labels', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('quality_summary', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('release_stage', sa.String(length=16), nullable=False),
    sa.Column('parent_version_id', sa.String(length=40), nullable=True),
    sa.Column('author_id', sa.String(length=40), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload_deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.CheckConstraint("release_stage IN ('draft','published','deprecated','archived')", name=op.f('ck_dataset_versions_known_dataset_release_stage')),
    sa.CheckConstraint('row_count >= 0', name=op.f('ck_dataset_versions_non_negative_row_count')),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name=op.f('fk_dataset_versions_dataset_id_datasets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_dataset_versions_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_versions')),
    sa.UniqueConstraint('dataset_id', 'dataset_hash', name='unique_dataset_hash'),
    sa.UniqueConstraint('dataset_id', 'version_number', name='unique_dataset_version_number')
    )
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_dataset_hash'), ['dataset_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_project_id'), ['project_id'], unique=False)

    op.create_table('experiment_runs',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('experiment_id', sa.String(length=40), nullable=False),
    sa.Column('prompt_version_id', sa.String(length=40), nullable=True),
    sa.Column('model_version_id', sa.String(length=40), nullable=True),
    sa.Column('dataset_version_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.CheckConstraint("status IN ('running','completed','failed','cancelled')", name=op.f('ck_experiment_runs_known_run_status')),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_runs_experiment_id_experiments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_experiment_runs_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_runs'))
    )
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_experiment_runs_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_runs_experiment_id'), ['experiment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_runs_model_version_id'), ['model_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_runs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_experiment_runs_prompt_version_id'), ['prompt_version_id'], unique=False)

    op.create_table('prompt_versions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('prompt_id', sa.String(length=40), nullable=False),
    sa.Column('project_id', sa.String(length=40), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=80), nullable=False),
    sa.Column('messages', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('variable_schema', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('default_variables', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('template_engine', sa.String(length=32), nullable=False),
    sa.Column('release_stage', sa.String(length=16), nullable=False),
    sa.Column('parent_version_id', sa.String(length=40), nullable=True),
    sa.Column('commit_message', sa.Text(), nullable=True),
    sa.Column('author_id', sa.String(length=40), nullable=True),
    sa.Column('evaluation', sa.JSON().with_variant(postgresql.JSONB(), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.CheckConstraint("release_stage IN ('draft','published','deprecated','archived')", name=op.f('ck_prompt_versions_known_release_stage')),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_prompt_versions_positive_version_number')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_prompt_versions_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_prompt_versions_prompt_id_prompts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_versions')),
    sa.UniqueConstraint('prompt_id', 'content_hash', name='unique_prompt_content_hash'),
    sa.UniqueConstraint('prompt_id', 'version_number', name='unique_prompt_version_number')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_versions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_versions_parent_version_id'), ['parent_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_versions_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_prompt_versions_project_stage', ['project_id', 'release_stage'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_versions_prompt_id'), ['prompt_id'], unique=False)

    op.create_table('dataset_files',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=40), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=80), nullable=False),
    sa.Column('row_count', sa.BigInteger(), nullable=False),
    sa.Column('split', sa.String(length=64), nullable=True),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], name=op.f('fk_dataset_files_dataset_version_id_dataset_versions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_dataset_files_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dataset_files')),
    sa.UniqueConstraint('dataset_version_id', 'sequence', name='unique_file_sequence')
    )
    with op.batch_alter_table('dataset_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_files_dataset_version_id'), ['dataset_version_id'], unique=False)
        batch_op.create_index('ix_dataset_files_object_key', ['object_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_files_organization_id'), ['organization_id'], unique=False)

    op.create_table('prompt_aliases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('prompt_id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version_id', sa.String(length=40), nullable=False),
    sa.Column('previous_version_id', sa.String(length=40), nullable=True),
    sa.Column('promoted_by', sa.String(length=40), nullable=True),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('organization_id', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_prompt_aliases_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name=op.f('fk_prompt_aliases_prompt_id_prompts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['prompt_versions.id'], name=op.f('fk_prompt_aliases_version_id_prompt_versions'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prompt_aliases')),
    sa.UniqueConstraint('prompt_id', 'name', name='unique_alias_per_prompt')
    )
    with op.batch_alter_table('prompt_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_aliases_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prompt_aliases_prompt_id'), ['prompt_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_aliases_prompt_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_aliases_organization_id'))

    op.drop_table('prompt_aliases')
    with op.batch_alter_table('dataset_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_files_organization_id'))
        batch_op.drop_index('ix_dataset_files_object_key')
        batch_op.drop_index(batch_op.f('ix_dataset_files_dataset_version_id'))

    op.drop_table('dataset_files')
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_prompt_id'))
        batch_op.drop_index('ix_prompt_versions_project_stage')
        batch_op.drop_index(batch_op.f('ix_prompt_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_versions_parent_version_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_versions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_prompt_versions_created_at'))
        batch_op.drop_index(batch_op.f('ix_prompt_versions_content_hash'))

    op.drop_table('prompt_versions')
    with op.batch_alter_table('experiment_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiment_runs_prompt_version_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_runs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_runs_model_version_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_runs_experiment_id'))
        batch_op.drop_index(batch_op.f('ix_experiment_runs_dataset_version_id'))

    op.drop_table('experiment_runs')
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_dataset_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_dataset_hash'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_created_at'))

    op.drop_table('dataset_versions')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_project_id'))
        batch_op.drop_index('ix_api_keys_project_active')
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_organization_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_environment_id'))

    op.drop_table('api_keys')
    with op.batch_alter_table('saved_views', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_views_project_id'))
        batch_op.drop_index(batch_op.f('ix_saved_views_organization_id'))

    op.drop_table('saved_views')
    with op.batch_alter_table('retention_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_retention_policies_project_id'))
        batch_op.drop_index(batch_op.f('ix_retention_policies_organization_id'))
        batch_op.drop_index(batch_op.f('ix_retention_policies_environment_id'))

    op.drop_table('retention_policies')
    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompts_project_id'))
        batch_op.drop_index(batch_op.f('ix_prompts_organization_id'))

    op.drop_table('prompts')
    with op.batch_alter_table('price_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_entries_price_book_id'))
        batch_op.drop_index('ix_price_entries_lookup')
        batch_op.drop_index('ix_price_entries_book_model')

    op.drop_table('price_entries')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_project_id'))
        batch_op.drop_index(batch_op.f('ix_model_versions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_model_versions_model_id'))
        batch_op.drop_index(batch_op.f('ix_model_versions_created_at'))
        batch_op.drop_index(batch_op.f('ix_model_versions_config_hash'))

    op.drop_table('model_versions')
    with op.batch_alter_table('experiments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_experiments_project_id'))
        batch_op.drop_index(batch_op.f('ix_experiments_organization_id'))

    op.drop_table('experiments')
    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_environments_project_id'))
        batch_op.drop_index(batch_op.f('ix_environments_organization_id'))

    op.drop_table('environments')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_project_id'))
        batch_op.drop_index(batch_op.f('ix_datasets_organization_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('stored_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_objects_project_id'))
        batch_op.drop_index(batch_op.f('ix_stored_objects_owner_id'))
        batch_op.drop_index(batch_op.f('ix_stored_objects_organization_id'))
        batch_op.drop_index(batch_op.f('ix_stored_objects_kind'))
        batch_op.drop_index('ix_stored_objects_expiry_sweep')
        batch_op.drop_index(batch_op.f('ix_stored_objects_expires_at'))
        batch_op.drop_index(batch_op.f('ix_stored_objects_created_at'))

    op.drop_table('stored_objects')
    with op.batch_alter_table('service_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_accounts_prefix'))
        batch_op.drop_index(batch_op.f('ix_service_accounts_organization_id'))

    op.drop_table('service_accounts')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_organization_id'))

    op.drop_table('projects')
    with op.batch_alter_table('price_books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_books_organization_id'))

    op.drop_table('price_books')
    with op.batch_alter_table('model_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_definitions_project_id'))
        batch_op.drop_index(batch_op.f('ix_model_definitions_organization_id'))

    op.drop_table('model_definitions')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('ingest_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_batches_received_at'))
        batch_op.drop_index(batch_op.f('ix_ingest_batches_project_id'))
        batch_op.drop_index(batch_op.f('ix_ingest_batches_organization_id'))
        batch_op.drop_index('ix_ingest_batches_org_received')
        batch_op.drop_index(batch_op.f('ix_ingest_batches_api_key_id'))

    op.drop_table('ingest_batches')
    with op.batch_alter_table('idempotency_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_records_organization_id'))
        batch_op.drop_index(batch_op.f('ix_idempotency_records_expires_at'))

    op.drop_table('idempotency_records')
    with op.batch_alter_table('export_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_export_jobs_requested_by'))
        batch_op.drop_index(batch_op.f('ix_export_jobs_project_id'))
        batch_op.drop_index(batch_op.f('ix_export_jobs_organization_id'))
        batch_op.drop_index('ix_export_jobs_org_status')
        batch_op.drop_index(batch_op.f('ix_export_jobs_created_at'))

    op.drop_table('export_jobs')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_organization_id'))
        batch_op.drop_index('ix_audit_events_org_occurred')
        batch_op.drop_index('ix_audit_events_org_action_occurred')
        batch_op.drop_index(batch_op.f('ix_audit_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_oidc_subject_unique')
        batch_op.drop_index(batch_op.f('ix_users_oidc_subject'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('outbox_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_outbox_unpublished')
        batch_op.drop_index(batch_op.f('ix_outbox_messages_created_at'))

    op.drop_table('outbox_messages')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    op.drop_table('bus_offsets')
    with op.batch_alter_table('bus_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_bus_messages_topic_partition_id')
        batch_op.drop_index(batch_op.f('ix_bus_messages_topic'))

    op.drop_table('bus_messages')
    with op.batch_alter_table('bus_dead_letters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bus_dead_letters_topic'))
        batch_op.drop_index('ix_bus_dead_letters_pending')
        batch_op.drop_index(batch_op.f('ix_bus_dead_letters_dead_lettered_at'))

    op.drop_table('bus_dead_letters')
    # ### end Alembic commands ###
