/**
 * Test fixtures.
 *
 * Built from the real schema types, so a change to the API contract breaks the
 * tests at compile time rather than producing components that render nothing.
 */

import type {
  AgentGraph,
  RetrievalStage,
  Span,
  Trace,
  TraceDetail,
} from "@aiobs/schemas";

const BASE = "2026-03-01T10:00:00.000Z";

export function makeSpan(
  overrides: Partial<Span> & Pick<Span, "span_id">,
): Span {
  return {
    trace_id: "a".repeat(32),
    parent_span_id: null,
    name: "span",
    kind: "internal",
    category: "custom",
    status: "ok",
    status_message: "",
    error_type: "",
    error_message: "",
    start_time: BASE,
    end_time: "2026-03-01T10:00:01.000Z",
    duration_ms: 1000,
    self_time_ms: 1000,
    on_critical_path: false,
    service_name: "api",
    service_version: "1.0.0",
    provider: "",
    model: "",
    prompt_name: "",
    prompt_version_id: "",
    model_config_id: "",
    dataset_version_id: "",
    knowledge_base_version: "",
    input_tokens: null,
    output_tokens: null,
    total_tokens: null,
    cached_input_tokens: null,
    reasoning_tokens: null,
    usage_source: "missing",
    cost: null,
    cost_currency: "USD",
    cost_status: "unpriced",
    time_to_first_token_ms: null,
    agent_id: "",
    tool_name: "",
    tool_status: "",
    retriever_name: "",
    input_preview: "",
    output_preview: "",
    input_ref: "",
    output_ref: "",
    attributes: {},
    links: [],
    late_arrival: false,
    ...overrides,
  } as Span;
}

export function makeTrace(overrides: Partial<Trace> = {}): Trace {
  return {
    trace_id: "a".repeat(32),
    name: "POST /chat",
    environment: "production",
    status: "ok",
    start_time: BASE,
    end_time: "2026-03-01T10:00:02.000Z",
    duration_ms: 2000,
    span_count: 3,
    error_count: 0,
    session_id: "",
    subject_id: "",
    release: "",
    tags: [],
    input_tokens: 100,
    output_tokens: 50,
    total_tokens: 150,
    cached_input_tokens: 0,
    usage_source: "provider",
    cost: "0.0012345",
    cost_currency: "USD",
    cost_status: "final",
    time_to_first_token_ms: 250,
    models: ["gpt-4o"],
    providers: ["openai"],
    prompt_version_ids: [],
    model_config_ids: [],
    dataset_version_ids: [],
    service_names: ["api"],
    llm_call_count: 1,
    retrieval_count: 1,
    tool_call_count: 0,
    agent_step_count: 0,
    complete: true,
    ...overrides,
  } as Trace;
}

/**
 * A three-span trace: root → retrieval, root → generation.
 * The generation is on the critical path; the retrieval is not.
 */
export function makeTraceDetail(
  overrides: Partial<TraceDetail> = {},
): TraceDetail {
  const root = makeSpan({
    span_id: "root",
    name: "POST /chat",
    category: "workflow_step",
    duration_ms: 2000,
    on_critical_path: true,
  });
  const retrieval = makeSpan({
    span_id: "retrieve",
    parent_span_id: "root",
    name: "vector.search",
    category: "retrieval",
    start_time: "2026-03-01T10:00:00.100Z",
    end_time: "2026-03-01T10:00:00.400Z",
    duration_ms: 300,
    retriever_name: "pgvector",
  });
  const generation = makeSpan({
    span_id: "generate",
    parent_span_id: "root",
    name: "openai.chat",
    category: "llm_generation",
    start_time: "2026-03-01T10:00:00.400Z",
    end_time: "2026-03-01T10:00:01.900Z",
    duration_ms: 1500,
    provider: "openai",
    model: "gpt-4o",
    input_tokens: 100,
    output_tokens: 50,
    total_tokens: 150,
    usage_source: "provider",
    cost: "0.0012345",
    cost_status: "final",
    on_critical_path: true,
  });

  return {
    trace: makeTrace(),
    spans: [root, retrieval, generation],
    events: [],
    cost_records: [
      {
        span_id: "generate",
        provider: "openai",
        model: "gpt-4o",
        currency: "USD",
        total: "0.0012345",
        price_book_version: "2026.01",
        estimation_status: "final",
        usage_source: "provider",
        components: [
          {
            category: "input",
            quantity: "100",
            unit_quantity: 1_000_000,
            unit_price: "2.50",
            amount: "0.00025",
            currency: "USD",
          },
        ],
        formula: "(100 / 1000000) * 2.50 = 0.00025",
      },
    ],
    critical_path: ["root", "generate"],
    children: { "": ["root"], root: ["retrieve", "generate"] },
    orphan_span_ids: [],
    services: ["api"],
    retry_groups: {},
    ...overrides,
  } as TraceDetail;
}

export function makeRetrievalStage(
  overrides: Partial<RetrievalStage> = {},
): RetrievalStage {
  return {
    span_id: "retrieve",
    span_name: "vector.search",
    query: "how do refunds work?",
    rewritten_query: "refund policy details",
    retriever_name: "pgvector",
    knowledge_base_version: "kb-2026-02",
    embedding_model: "text-embedding-3-small",
    search_type: "hybrid",
    latency_ms: 300,
    embedding_latency_ms: 40,
    reranker_latency_ms: 90,
    reranker_model: "rerank-v3",
    stages: [
      {
        stage: "query",
        label: "Query",
        detail: "how do refunds work?",
        latency_ms: null,
        present: true,
      },
      {
        stage: "rewrite",
        label: "Rewrite",
        detail: "refund policy details",
        latency_ms: 12,
        present: true,
      },
      {
        stage: "embed",
        label: "Embed",
        detail: "text-embedding-3-small",
        latency_ms: 40,
        present: true,
      },
      {
        stage: "retrieve",
        label: "Retrieve",
        detail: "hybrid, 3 docs",
        latency_ms: 150,
        present: true,
      },
      {
        stage: "rerank",
        label: "Rerank",
        detail: "rerank-v3",
        latency_ms: 90,
        present: true,
      },
      {
        stage: "select",
        label: "Select",
        detail: "2 of 3 selected",
        latency_ms: null,
        present: true,
      },
      {
        stage: "generate",
        label: "Generate",
        detail: "gpt-4o",
        latency_ms: null,
        present: true,
      },
    ],
    documents: [
      {
        document_id: "doc-1",
        chunk_id: "doc-1#0",
        rank: 1,
        rerank_rank: 2,
        score: 0.8123,
        rerank_score: 0.51,
        title: "Refund policy",
        content: "Refunds are issued within 30 days.",
        content_ref: "",
        source: "https://example.test/refunds",
        token_count: 120,
        selected: true,
        truncated: false,
      },
      {
        document_id: "doc-2",
        chunk_id: "doc-2#0",
        rank: 2,
        rerank_rank: 1,
        score: 0.8005,
        rerank_score: 0.77,
        title: "Returns",
        content: "Returns must be postmarked within 14 days.",
        content_ref: "",
        source: "https://example.test/returns",
        token_count: 95,
        selected: true,
        truncated: false,
      },
      {
        document_id: "doc-3",
        chunk_id: "doc-3#0",
        rank: 3,
        rerank_rank: 3,
        score: 0.4102,
        rerank_score: 0.11,
        title: "Shipping",
        content: "Orders ship in two days.",
        content_ref: "",
        source: "",
        token_count: 80,
        selected: false,
        truncated: false,
      },
    ],
    diagnostics: {
      document_count: 3,
      selected_count: 2,
      unused_count: 1,
      unused_ratio: 1 / 3,
      score_min: 0.4102,
      score_max: 0.8123,
      score_mean: 0.6743,
      score_stddev: 0.18,
      score_margin: 0.0118,
      reranked: true,
      mean_rank_movement: 0.67,
      rerank_promotions: 1,
      rerank_demotions: 1,
      duplicate_document_ids: [],
      near_duplicate_pairs: [],
      context_tokens: 215,
      truncated_count: 0,
      missing_source_count: 1,
      empty_result: false,
    },
    ...overrides,
  } as RetrievalStage;
}

export function makeAgentGraph(
  overrides: Partial<AgentGraph> = {},
): AgentGraph {
  return {
    nodes: [
      {
        id: "step-1",
        step_number: 1,
        agent_id: "planner",
        step_type: "plan",
        label: "Decide next action",
        status: "ok",
        span_id: "span-1",
        duration_ms: 120,
        tool_name: "",
        tool_status: "",
        decision_summary: "Search the knowledge base before answering.",
        input_tokens: 40,
        output_tokens: 12,
        cost_total: "0.0000400",
        branch_id: "main",
        loop_iteration: null,
        is_retry: false,
        approval_status: "not_required",
        termination_reason: "",
        error_message: "",
        on_critical_path: true,
      },
      {
        id: "step-2",
        step_number: 2,
        agent_id: "planner",
        step_type: "tool_call",
        label: "search_docs",
        status: "error",
        span_id: "span-2",
        duration_ms: 640,
        tool_name: "search_docs",
        tool_status: "error",
        decision_summary: "",
        input_tokens: null,
        output_tokens: null,
        cost_total: null,
        branch_id: "main",
        loop_iteration: null,
        is_retry: false,
        approval_status: "not_required",
        termination_reason: "",
        error_message: "upstream timeout",
        on_critical_path: true,
      },
      {
        id: "step-3",
        step_number: 3,
        agent_id: "planner",
        step_type: "tool_call",
        label: "search_docs (retry)",
        status: "ok",
        span_id: "span-3",
        duration_ms: 210,
        tool_name: "search_docs",
        tool_status: "ok",
        decision_summary: "",
        input_tokens: null,
        output_tokens: null,
        cost_total: null,
        branch_id: "main",
        loop_iteration: null,
        is_retry: true,
        approval_status: "not_required",
        termination_reason: "",
        error_message: "",
        on_critical_path: true,
      },
      {
        id: "step-4",
        step_number: 4,
        agent_id: "writer",
        step_type: "handoff",
        label: "Compose answer",
        status: "ok",
        span_id: "span-4",
        duration_ms: 900,
        tool_name: "",
        tool_status: "",
        decision_summary: "Enough context gathered; write the answer.",
        input_tokens: 800,
        output_tokens: 210,
        cost_total: "0.0031000",
        branch_id: "writer",
        loop_iteration: null,
        is_retry: false,
        approval_status: "not_required",
        termination_reason: "answered",
        error_message: "",
        on_critical_path: true,
      },
    ],
    edges: [
      { source: "step-1", target: "step-2", kind: "sequence", label: "" },
      { source: "step-2", target: "step-3", kind: "retry", label: "attempt 2" },
      {
        source: "step-3",
        target: "step-4",
        kind: "handoff",
        label: "planner → writer",
      },
    ],
    agents: ["planner", "writer"],
    branches: ["main", "writer"],
    max_steps: 10,
    termination_reason: "answered",
    total_steps: 4,
    retry_count: 1,
    loop_detected: false,
    handoff_count: 1,
    truncated: false,
    ...overrides,
  } as AgentGraph;
}
