#!/usr/bin/env python
"""Regenerate the SDK's copy of the semantic-convention constants.

The SDK cannot import ``aiobs_schemas`` -- installing it must not drag the
platform's schema package into a customer application -- so the constants are
generated into ``packages/python-sdk/src/aiobs/semconv.py`` and a contract test
asserts the two stay identical.

Usage:  python scripts/gen-sdk-semconv.py
"""

from __future__ import annotations

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages" / "shared-schemas" / "python"))

import aiobs_schemas.semconv as source  # noqa: E402

TARGET = ROOT / "packages" / "python-sdk" / "src" / "aiobs" / "semconv.py"

HEADER = '''"""Semantic convention constants (SDK copy).

Mirrors ``aiobs_schemas.semconv`` so that installing the SDK requires only
``httpx``. Generated by ``scripts/gen-sdk-semconv.py``; asserted identical to
the source of truth by ``tests/contract/test_sdk_semconv_parity.py``.

Do not edit by hand -- regenerate instead.
"""

from __future__ import annotations

from typing import Final

'''


def main() -> int:
    names = sorted(
        name
        for name in dir(source)
        if name.isupper() and isinstance(getattr(source, name), str) and not name.startswith("_")
    )
    body = [f"{name}: Final = {getattr(source, name)!r}" for name in names]
    tail = [
        "",
        "#: Every constant defined here, for the parity test.",
        "ALL_ATTRIBUTES: Final[frozenset[str]] = frozenset(",
        "    {",
        *[f"        {name}," for name in names],
        "    }",
        ")",
        "",
    ]
    TARGET.write_text(HEADER + "\n".join(body) + "\n" + "\n".join(tail))
    print(f"wrote {len(names)} constants to {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
