"""Semantic convention constants (SDK copy).

Mirrors ``aiobs_schemas.semconv`` so that installing the SDK requires only
``httpx``. Generated by ``scripts/gen-sdk-semconv.py``; asserted identical to
the source of truth by ``tests/contract/test_sdk_semconv_parity.py``.

Do not edit by hand -- regenerate instead.
"""

from __future__ import annotations

from typing import Final

AGENT_APPROVAL_REQUIRED: Final = "aiobs.agent.approval.required"
AGENT_APPROVAL_STATUS: Final = "aiobs.agent.approval.status"
AGENT_BRANCH_ID: Final = "aiobs.agent.branch.id"
AGENT_DECISION_SUMMARY: Final = "aiobs.agent.decision_summary"
AGENT_GOAL: Final = "aiobs.agent.goal"
AGENT_HANDOFF_TARGET: Final = "aiobs.agent.handoff.target"
AGENT_ID: Final = "aiobs.agent.id"
AGENT_LOOP_ITERATION: Final = "aiobs.agent.loop.iteration"
AGENT_MAX_STEPS: Final = "aiobs.agent.max_steps"
AGENT_MEMORY_READ_KEYS: Final = "aiobs.agent.memory.read_keys"
AGENT_MEMORY_WRITE_KEYS: Final = "aiobs.agent.memory.write_keys"
AGENT_RETRY_OF: Final = "aiobs.agent.retry_of"
AGENT_STEP_NUMBER: Final = "aiobs.agent.step.number"
AGENT_STEP_PARENT: Final = "aiobs.agent.step.parent"
AGENT_STEP_TYPE: Final = "aiobs.agent.step.type"
AGENT_TERMINATION_REASON: Final = "aiobs.agent.termination_reason"
AGENT_TOOL_ARGUMENTS: Final = "aiobs.agent.tool.arguments"
AGENT_TOOL_NAME: Final = "aiobs.agent.tool.name"
AGENT_TOOL_RESULT_REF: Final = "aiobs.agent.tool.result_ref"
AGENT_TOOL_STATUS: Final = "aiobs.agent.tool.status"
AGENT_VERSION: Final = "aiobs.agent.version"
COST_CURRENCY: Final = "aiobs.cost.currency"
COST_ESTIMATED: Final = "aiobs.cost.estimated"
COST_PRICE_BOOK_VERSION: Final = "aiobs.cost.price_book_version"
COST_TOTAL: Final = "aiobs.cost.total"
DATASET_NAME: Final = "aiobs.dataset.name"
DATASET_RECORD_ID: Final = "aiobs.dataset.record_id"
DATASET_VERSION_ID: Final = "aiobs.dataset.version_id"
DB_QUERY_TEXT: Final = "db.query.text"
DB_SYSTEM: Final = "db.system.name"
DEPLOYMENT_ENVIRONMENT: Final = "deployment.environment.name"
EVENT_EXCEPTION: Final = "exception"
EVENT_FIRST_TOKEN: Final = "aiobs.first_token"
EVENT_HUMAN_APPROVAL: Final = "aiobs.human_approval"
EVENT_LOG: Final = "aiobs.log"
EVENT_RETRY: Final = "aiobs.retry"
EVENT_STREAM_CHUNK: Final = "aiobs.stream_chunk"
EVENT_TRUNCATION: Final = "aiobs.truncation"
EXCEPTION_MESSAGE: Final = "exception.message"
EXCEPTION_STACKTRACE: Final = "exception.stacktrace"
EXCEPTION_TYPE: Final = "exception.type"
EXPERIMENT_ID: Final = "aiobs.experiment.id"
EXPERIMENT_RUN_ID: Final = "aiobs.experiment.run_id"
GEN_AI_AGENT_ID: Final = "gen_ai.agent.id"
GEN_AI_AGENT_NAME: Final = "gen_ai.agent.name"
GEN_AI_CONVERSATION_ID: Final = "gen_ai.conversation.id"
GEN_AI_OPERATION_NAME: Final = "gen_ai.operation.name"
GEN_AI_REQUEST_ENCODING_FORMATS: Final = "gen_ai.request.encoding_formats"
GEN_AI_REQUEST_FREQUENCY_PENALTY: Final = "gen_ai.request.frequency_penalty"
GEN_AI_REQUEST_MAX_TOKENS: Final = "gen_ai.request.max_tokens"
GEN_AI_REQUEST_MODEL: Final = "gen_ai.request.model"
GEN_AI_REQUEST_PRESENCE_PENALTY: Final = "gen_ai.request.presence_penalty"
GEN_AI_REQUEST_SEED: Final = "gen_ai.request.seed"
GEN_AI_REQUEST_STOP_SEQUENCES: Final = "gen_ai.request.stop_sequences"
GEN_AI_REQUEST_TEMPERATURE: Final = "gen_ai.request.temperature"
GEN_AI_REQUEST_TOP_K: Final = "gen_ai.request.top_k"
GEN_AI_REQUEST_TOP_P: Final = "gen_ai.request.top_p"
GEN_AI_RESPONSE_FINISH_REASONS: Final = "gen_ai.response.finish_reasons"
GEN_AI_RESPONSE_ID: Final = "gen_ai.response.id"
GEN_AI_RESPONSE_MODEL: Final = "gen_ai.response.model"
GEN_AI_SYSTEM: Final = "gen_ai.system"
GEN_AI_TOOL_CALL_ID: Final = "gen_ai.tool.call.id"
GEN_AI_TOOL_NAME: Final = "gen_ai.tool.name"
GEN_AI_USAGE_INPUT_TOKENS: Final = "gen_ai.usage.input_tokens"
GEN_AI_USAGE_OUTPUT_TOKENS: Final = "gen_ai.usage.output_tokens"
GIT_COMMIT: Final = "aiobs.git.commit"
GUARDRAIL_NAME: Final = "aiobs.guardrail.name"
GUARDRAIL_OUTCOME: Final = "aiobs.guardrail.outcome"
GUARDRAIL_SCORE: Final = "aiobs.guardrail.score"
HTTP_REQUEST_METHOD: Final = "http.request.method"
HTTP_RESPONSE_STATUS_CODE: Final = "http.response.status_code"
INPUT_BYTES: Final = "aiobs.input.bytes"
INPUT_REF: Final = "aiobs.input.ref"
INPUT_TRUNCATED: Final = "aiobs.input.truncated"
INPUT_VALUE: Final = "aiobs.input.value"
KNOWLEDGE_BASE_VERSION: Final = "aiobs.knowledge_base.version"
LATENCY_PROVIDER_MS: Final = "aiobs.latency.provider_ms"
LATENCY_QUEUE_MS: Final = "aiobs.latency.queue_ms"
LATENCY_STREAM_MS: Final = "aiobs.latency.stream_ms"
LATENCY_TIME_TO_FIRST_TOKEN_MS: Final = "aiobs.latency.time_to_first_token_ms"
MESSAGING_DESTINATION_NAME: Final = "messaging.destination.name"
MESSAGING_SYSTEM: Final = "messaging.system"
MODEL_CONFIG_HASH: Final = "aiobs.model.config_hash"
MODEL_CONFIG_ID: Final = "aiobs.model.config_id"
MODEL_DEPLOYMENT: Final = "aiobs.model.deployment"
MODEL_FAMILY: Final = "aiobs.model.family"
MODEL_REGION: Final = "aiobs.model.region"
MODEL_SYSTEM_FINGERPRINT: Final = "aiobs.model.system_fingerprint"
OUTPUT_BYTES: Final = "aiobs.output.bytes"
OUTPUT_REF: Final = "aiobs.output.ref"
OUTPUT_TRUNCATED: Final = "aiobs.output.truncated"
OUTPUT_VALUE: Final = "aiobs.output.value"
PROJECT_ID: Final = "aiobs.project.id"
PROMPT_HASH: Final = "aiobs.prompt.hash"
PROMPT_NAME: Final = "aiobs.prompt.name"
PROMPT_VARIABLES: Final = "aiobs.prompt.variables"
PROMPT_VERSION_ID: Final = "aiobs.prompt.version_id"
PROMPT_VERSION_LABEL: Final = "aiobs.prompt.version_label"
REDACTED_KEYS: Final = "aiobs.redacted.keys"
RELEASE: Final = "aiobs.release"
RETRIEVAL_CONTEXT_TOKENS: Final = "aiobs.retrieval.context_tokens"
RETRIEVAL_CONTEXT_TRUNCATED: Final = "aiobs.retrieval.context_truncated"
RETRIEVAL_DOCUMENTS: Final = "aiobs.retrieval.documents"
RETRIEVAL_EMBEDDING_DIMENSIONS: Final = "aiobs.retrieval.embedding.dimensions"
RETRIEVAL_EMBEDDING_LATENCY_MS: Final = "aiobs.retrieval.embedding.latency_ms"
RETRIEVAL_EMBEDDING_MODEL: Final = "aiobs.retrieval.embedding.model"
RETRIEVAL_FILTERS: Final = "aiobs.retrieval.filters"
RETRIEVAL_LATENCY_MS: Final = "aiobs.retrieval.latency_ms"
RETRIEVAL_QUERY: Final = "aiobs.retrieval.query"
RETRIEVAL_RERANKER_LATENCY_MS: Final = "aiobs.retrieval.reranker.latency_ms"
RETRIEVAL_RERANKER_MODEL: Final = "aiobs.retrieval.reranker.model"
RETRIEVAL_RESULT_COUNT: Final = "aiobs.retrieval.result_count"
RETRIEVAL_RETRIEVER_NAME: Final = "aiobs.retrieval.retriever.name"
RETRIEVAL_RETRIEVER_VERSION: Final = "aiobs.retrieval.retriever.version"
RETRIEVAL_REWRITTEN_QUERY: Final = "aiobs.retrieval.rewritten_query"
RETRIEVAL_SEARCH_TYPE: Final = "aiobs.retrieval.search_type"
RETRIEVAL_TOP_K: Final = "aiobs.retrieval.top_k"
SAMPLING_DECISION: Final = "aiobs.sampling.decision"
SAMPLING_RATE: Final = "aiobs.sampling.rate"
SDK_NAME: Final = "aiobs.sdk.name"
SDK_VERSION: Final = "aiobs.sdk.version"
SERVICE_INSTANCE_ID: Final = "service.instance.id"
SERVICE_NAME: Final = "service.name"
SERVICE_VERSION: Final = "service.version"
SESSION_ID: Final = "aiobs.session.id"
SPAN_CATEGORY: Final = "aiobs.span.category"
SUBJECT_ID: Final = "aiobs.subject.id"
TAGS: Final = "aiobs.tags"
TELEMETRY_SDK_LANGUAGE: Final = "telemetry.sdk.language"
TELEMETRY_SDK_NAME: Final = "telemetry.sdk.name"
TELEMETRY_SDK_VERSION: Final = "telemetry.sdk.version"
TENANT_ID: Final = "aiobs.tenant.id"
TRACE_NAME: Final = "aiobs.trace.name"
URL_FULL: Final = "url.full"
USAGE_AUDIO_INPUT_SECONDS: Final = "aiobs.usage.audio_input_seconds"
USAGE_AUDIO_OUTPUT_SECONDS: Final = "aiobs.usage.audio_output_seconds"
USAGE_CACHED_INPUT_TOKENS: Final = "aiobs.usage.cached_input_tokens"
USAGE_CACHE_WRITE_TOKENS: Final = "aiobs.usage.cache_write_tokens"
USAGE_IMAGE_INPUT_COUNT: Final = "aiobs.usage.image_input_count"
USAGE_IMAGE_OUTPUT_COUNT: Final = "aiobs.usage.image_output_count"
USAGE_INPUT_TOKENS: Final = "aiobs.usage.input_tokens"
USAGE_OUTPUT_TOKENS: Final = "aiobs.usage.output_tokens"
USAGE_RAW: Final = "aiobs.usage.raw"
USAGE_REASONING_TOKENS: Final = "aiobs.usage.reasoning_tokens"
USAGE_SOURCE: Final = "aiobs.usage.source"
USAGE_TOTAL_TOKENS: Final = "aiobs.usage.total_tokens"

#: Every constant defined here, for the parity test.
ALL_ATTRIBUTES: Final[frozenset[str]] = frozenset(
    {
        AGENT_APPROVAL_REQUIRED,
        AGENT_APPROVAL_STATUS,
        AGENT_BRANCH_ID,
        AGENT_DECISION_SUMMARY,
        AGENT_GOAL,
        AGENT_HANDOFF_TARGET,
        AGENT_ID,
        AGENT_LOOP_ITERATION,
        AGENT_MAX_STEPS,
        AGENT_MEMORY_READ_KEYS,
        AGENT_MEMORY_WRITE_KEYS,
        AGENT_RETRY_OF,
        AGENT_STEP_NUMBER,
        AGENT_STEP_PARENT,
        AGENT_STEP_TYPE,
        AGENT_TERMINATION_REASON,
        AGENT_TOOL_ARGUMENTS,
        AGENT_TOOL_NAME,
        AGENT_TOOL_RESULT_REF,
        AGENT_TOOL_STATUS,
        AGENT_VERSION,
        COST_CURRENCY,
        COST_ESTIMATED,
        COST_PRICE_BOOK_VERSION,
        COST_TOTAL,
        DATASET_NAME,
        DATASET_RECORD_ID,
        DATASET_VERSION_ID,
        DB_QUERY_TEXT,
        DB_SYSTEM,
        DEPLOYMENT_ENVIRONMENT,
        EVENT_EXCEPTION,
        EVENT_FIRST_TOKEN,
        EVENT_HUMAN_APPROVAL,
        EVENT_LOG,
        EVENT_RETRY,
        EVENT_STREAM_CHUNK,
        EVENT_TRUNCATION,
        EXCEPTION_MESSAGE,
        EXCEPTION_STACKTRACE,
        EXCEPTION_TYPE,
        EXPERIMENT_ID,
        EXPERIMENT_RUN_ID,
        GEN_AI_AGENT_ID,
        GEN_AI_AGENT_NAME,
        GEN_AI_CONVERSATION_ID,
        GEN_AI_OPERATION_NAME,
        GEN_AI_REQUEST_ENCODING_FORMATS,
        GEN_AI_REQUEST_FREQUENCY_PENALTY,
        GEN_AI_REQUEST_MAX_TOKENS,
        GEN_AI_REQUEST_MODEL,
        GEN_AI_REQUEST_PRESENCE_PENALTY,
        GEN_AI_REQUEST_SEED,
        GEN_AI_REQUEST_STOP_SEQUENCES,
        GEN_AI_REQUEST_TEMPERATURE,
        GEN_AI_REQUEST_TOP_K,
        GEN_AI_REQUEST_TOP_P,
        GEN_AI_RESPONSE_FINISH_REASONS,
        GEN_AI_RESPONSE_ID,
        GEN_AI_RESPONSE_MODEL,
        GEN_AI_SYSTEM,
        GEN_AI_TOOL_CALL_ID,
        GEN_AI_TOOL_NAME,
        GEN_AI_USAGE_INPUT_TOKENS,
        GEN_AI_USAGE_OUTPUT_TOKENS,
        GIT_COMMIT,
        GUARDRAIL_NAME,
        GUARDRAIL_OUTCOME,
        GUARDRAIL_SCORE,
        HTTP_REQUEST_METHOD,
        HTTP_RESPONSE_STATUS_CODE,
        INPUT_BYTES,
        INPUT_REF,
        INPUT_TRUNCATED,
        INPUT_VALUE,
        KNOWLEDGE_BASE_VERSION,
        LATENCY_PROVIDER_MS,
        LATENCY_QUEUE_MS,
        LATENCY_STREAM_MS,
        LATENCY_TIME_TO_FIRST_TOKEN_MS,
        MESSAGING_DESTINATION_NAME,
        MESSAGING_SYSTEM,
        MODEL_CONFIG_HASH,
        MODEL_CONFIG_ID,
        MODEL_DEPLOYMENT,
        MODEL_FAMILY,
        MODEL_REGION,
        MODEL_SYSTEM_FINGERPRINT,
        OUTPUT_BYTES,
        OUTPUT_REF,
        OUTPUT_TRUNCATED,
        OUTPUT_VALUE,
        PROJECT_ID,
        PROMPT_HASH,
        PROMPT_NAME,
        PROMPT_VARIABLES,
        PROMPT_VERSION_ID,
        PROMPT_VERSION_LABEL,
        REDACTED_KEYS,
        RELEASE,
        RETRIEVAL_CONTEXT_TOKENS,
        RETRIEVAL_CONTEXT_TRUNCATED,
        RETRIEVAL_DOCUMENTS,
        RETRIEVAL_EMBEDDING_DIMENSIONS,
        RETRIEVAL_EMBEDDING_LATENCY_MS,
        RETRIEVAL_EMBEDDING_MODEL,
        RETRIEVAL_FILTERS,
        RETRIEVAL_LATENCY_MS,
        RETRIEVAL_QUERY,
        RETRIEVAL_RERANKER_LATENCY_MS,
        RETRIEVAL_RERANKER_MODEL,
        RETRIEVAL_RESULT_COUNT,
        RETRIEVAL_RETRIEVER_NAME,
        RETRIEVAL_RETRIEVER_VERSION,
        RETRIEVAL_REWRITTEN_QUERY,
        RETRIEVAL_SEARCH_TYPE,
        RETRIEVAL_TOP_K,
        SAMPLING_DECISION,
        SAMPLING_RATE,
        SDK_NAME,
        SDK_VERSION,
        SERVICE_INSTANCE_ID,
        SERVICE_NAME,
        SERVICE_VERSION,
        SESSION_ID,
        SPAN_CATEGORY,
        SUBJECT_ID,
        TAGS,
        TELEMETRY_SDK_LANGUAGE,
        TELEMETRY_SDK_NAME,
        TELEMETRY_SDK_VERSION,
        TENANT_ID,
        TRACE_NAME,
        URL_FULL,
        USAGE_AUDIO_INPUT_SECONDS,
        USAGE_AUDIO_OUTPUT_SECONDS,
        USAGE_CACHED_INPUT_TOKENS,
        USAGE_CACHE_WRITE_TOKENS,
        USAGE_IMAGE_INPUT_COUNT,
        USAGE_IMAGE_OUTPUT_COUNT,
        USAGE_INPUT_TOKENS,
        USAGE_OUTPUT_TOKENS,
        USAGE_RAW,
        USAGE_REASONING_TOKENS,
        USAGE_SOURCE,
        USAGE_TOTAL_TOKENS,
    }
)
